### ISSUE TITLE
Development not working

### ISSUE THREAD

**Issue by naofumi-fujii** [bdash-app/bdash#29]
i tried the following on readme
```
$ npm install -g yarn
$ cd bdash
$ yarn
$ npm run build:sqlite3
$ npm start
```

but it failed with this error
```
[naofumi.fujii]$ npm run start

> Bdash@1.2.1 start /Users/naofumi.fujii/src/github.com/bdash-app/bdash
> electron .

App threw an error during load
Error: Cannot find module './dist/main'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/naofumi.fujii/src/github.com/bdash-app/bdash/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/naofumi.fujii/src/github.com/bdash-app/bdash/index.js:1:156)
    at Object.<anonymous> (/Users/naofumi.fujii/src/github.com/bdash-app/bdash/index.js:3:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by hokaccha** [comment]
I updated the document for development, so please try it.
https://github.com/bdash-app/bdash/commit/69202761afcc0e02fb1a4a92ffaeb36bf292a8df

**Comment by naofumi-fujii** [comment]
thanks! its working 👍
